name: scraper
description: "A Flutter app for monitoring product availability"

# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client for making API requests
  http: ^1.2.0

  # Local notifications
  flutter_local_notifications: ^17.0.0

  # Persistent storage
  shared_preferences: ^2.2.2

  # HTML parsing
  html: ^0.15.4

  # Internationalization and date formatting
  intl: ^0.19.0

  # Permission handling
  permission_handler: ^11.1.0

  # Background service
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.3.0

  # UI components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets later:
  # assets:
  #   - images/logo.png

  # To add custom fonts later:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700